# Generated by Django 4.2.6 on 2023-11-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_remove_chat_message_remove_chat_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="messages",
        ),
        migrations.AddField(
            model_name="chat",
            name="conversation_history",
            field=models.JSONField(default=list),
        ),
    ]
