# Generated by Django 4.2.6 on 2023-11-16 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_remove_chat_messages_chat_message_chat_response"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="response",
        ),
        migrations.AddField(
            model_name="chat",
            name="messages",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="chat",
            name="assistant_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="thread_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
