# Generated by Django 4.2.6 on 2023-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_remove_chat_conversation_history_chat_messages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="messages",
        ),
        migrations.AddField(
            model_name="chat",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
