# Generated by Django 4.2.6 on 2023-11-17 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0007_rename_last_updated_chat_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="social_media",
        ),
    ]
