# Generated by Django 4.2.6 on 2023-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0008_remove_customuser_social_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
